on:
  push:
    branches:
      - feature/create-dockerfile
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      spring.datasource.url: ${{secrets.APP_SETTING_DATASOURCE_URL}}
      spring.datasource.username: ${{secrets.APP_SETTING_DATASOURCE_USERNAME}}
      spring.datasource.password: ${{secrets.APP_SETTING_DATASOURCE_PASSWORD}}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build Common & User Modules
        run: cd ./common && mvn install && cd ../user && mvn install && cd ../auth && mvn install && cd .. && mvn package
      - name: Make Directory for deliver
        run: mkdir deploy
      - name: Copy Jar
        run: cp ./target/*.jar ./deploy/
      - name: Print Directory
        run: ls -al ./deploy
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: user/app:latest




#      - name: Set up QEMU
#        uses: docker/setup-qemu-action@v2
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
#      - name: Login to DockerHub
#        uses: docker/login-action@v2
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_ACCESSTOKEN }}
#      - name: Build and push
#        uses: docker/build-push-action@v3
#        with:
#          push: true
#          tags: user/app:latest


